In [1]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# import the chicago data file
city_data = pd.read_csv('Data/chicago_data.csv')
city_data

,date,cases_total,deaths_total,hospitalizations_total,cases_age_0_17,cases_age_18_29,cases_age_30_39,cases_age_40_49,cases_age_50_59,cases_age_60_69,...,acute_non_icu_beds_in_use_covid_19,acute_non_icu_beds_in_use_covid_19_patients,acute_non_icu_beds_in_use_covid_19_pui,acute_non_icu_beds_in_use_non_covid_19,acute_non_icu_beds_available_total,combined_hospital_beds_in_use_covid_19,daily_update_pdf,ventilator_surge_capacity,icu_beds_surge_capacity_adult,icu_beds_surge_capacity_pediatric
0,2020-03-29T00:00:00.000,282,20,130.0,4,29,48,54,50,50,...,NaN,NaN,NaN,NaN,1638.0,NaN,{'url': 'https://www.chicago.gov/content/dam/c...,196.0,218.0,8.0
1,2020-03-01T00:00:00.000,0,0,2.0,0,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2020-03-02T00:00:00.000,0,0,2.0,0,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2020-03-03T00:00:00.000,0,0,3.0,0,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2020-03-04T00:00:00.000,0,0,4.0,0,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
232,2020-06-04T00:00:00.000,319,14,35.0,27,92,63,54,40,25,...,721.0,437.0,284.0,4593.0,2450.0,1033.0,{'url': 'https://www.chicago.gov/content/dam/c...,NaN,NaN,NaN
233,2020-07-15T00:00:00.000,267,7,24.0,30,83,51,33,34,18,...,423.0,184.0,239.0,5193.0,2421.0,521.0,{'url': 'https://www.chicago.gov/content/dam/c...,NaN,NaN,NaN
234,2020-07-13T00:00:00.000,335,3,35.0,36,98,68,45,35,31,...,361.0,161.0,200.0,5090.0,2592.0,467.0,{'url': 'https://www.chicago.gov/content/dam/c...,NaN,NaN,NaN
235,2020-05-14T00:00:00.000,776,45,130.0,49,167,152,132,108,95,...,1219.0,869.0,350.0,4824.0,1550.0,1675.0,{'url': 'https://www.chicago.gov/content/dam/c...,312.0,117.0,20.0
236,2020-10-22T00:00:00.000,2,0,NaN,0,0,0,1,0,1,...,443.0,226.0,217.0,5799.0,2003.0,559.0,{'url': 'https://www.chicago.gov/content/dam/c...,NaN,NaN,NaN

In [ ]:
# need to format the date column to something usable by matplotlib
# Need to find and replace NaN values with something.... 0?